### PR TITLE
Add Buildkite

### PR DESCRIPTION
**Pull request by jkmassel**
Adds Buildkite support alongside CircleCI – also removes the CircleCI-based publishing and:
- Adds rubocop and fixes issues
- Updates the Ruby version

**To Test**
- Note that CI passes in Buildkite and CircleCI
- Note that [Buildkite can successfully publish new versions](https://buildkite.com/wordpress-mobile/gridicons-ios/builds/5)

### CODE REVIEW

**Review by mokagio — APPROVED** [review]
Looking good.

Same comments as mentioned in https://github.com/Automattic/Matticspace-iOS/pull/158#pullrequestreview-727312746.

As an aside and a different conversation. I wonder if having a `Rakefile` and a `Fastfile` is redundant, and we should fold everything into the `Fastfile`? 🤔 Or is the idea behind using Rake for the setup tasks to lean into its built-in task dependency management?

**Comment by jkmassel** [comment]
For this project, we use the `Rakefile` to manage the `swiftgen` stuff, so realistically it could live anywhere – even just as a target within the Xcode project? 

IMHO that change would be great as part of a "remove ruby from all non-CI work" update – I think we could probably accomplish all the same using SwiftPM + a bash script target?

**Comment by mokagio** [comment]
> IMHO that change would be great as part of a "remove ruby from all non-CI work" update – I think we could probably accomplish all the same using SwiftPM + a bash script target?

I'm not sure about SPM + bash script target, but mainly because I'm not familiar with how SwiftGen works and how it's used here.

Definitely makes sense to tackle it as part of a Ruby removal, when or if the time will come for that. 👍

**Comment by AliSoftware** [comment]
We can definitively move the stuff in Rakefile elsewhere (in a separate PR).

> I'm not sure about SPM + bash script target, but mainly because I'm not familiar with how SwiftGen works and how it's used here.

The things that the Rakefile handles here are mainly "check if SwiftGen is installed (in the expected version)", "install it if not", and "invoke it". All those should totally be doable via simple shell commands or fastlane lanes instead.

In fact that logic and those steps is pretty much similar to [the ones I've implemented in my `ios_lint_localizations` action in the toolkit](https://github.com/wordpress-mobile/release-toolkit/blob/develop/lib/fastlane/plugin/wpmreleasetoolkit/actions/ios/ios_lint_localizations.rb#L21-L29) (in that action we're using SwiftGen to compare placeholder types used strings files, while in GridIcons we're using SwiftGen for its primary purpose, which is generate type-safe Swift constants for each asset/icon that library contains)

**Comment by mokagio** [comment]
Maybe we could extra the logic to check and install SwiftGen in a dedicated release toolkit action 🤔 🧐 

That could actually be a neat standalone Fastlane plugin, too.

**Comment by mokagio** [comment]
@jkmassel I can see the branch still exists. I'm 99% we can deleted, so I'll go ahead and do it, and turn on automatic branch deletion in this repo. 

Let me know if I missed something and there was a reason to keep the branch: 🙏

**Pull request merged**
